name: zflutter
description: A round, flat and designer-friendly pseudo-3D engine for Flutter
version: 0.0.1+3


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  alchemist: ^0.7.0


flutter:
